twindash/twindash/urls.py
from django.contrib import admin
from django.urls import path, include

from twinsapp import views

urlpatterns = [
    path('', views.index, name='home'),
    path('twinsapp/', include('twinsapp.urls')),
#    path('', include('twinsapp.urls')),
    path('admin/', admin.site.urls),
]

twindash/twinsapp/urls.py
from django.urls import path

from . import views

app_name = 'twinsapp'
urlpatterns = [
    path('', views.index, name='index'),
    # ex. /twinsapp/MAIA/
    path('<nombre_bebe>/', views.main_bebe, name='main_bebe'),
    # ex. /twinsapp/MAIA/2020/03/01/
    path('<nombre_bebe>/<int:year>/<int:month>/<int:day>/', views.bebe_dia, name='bebe_dia'),
    path('^tomas/$', views.resumen_tomas, name='resumen_tomas'),
]

twindash/twinsapp/models.py
from django.db import models

# Create your models here.
class Bebe(models.Model):
    nombre = models.CharField("Nombre de la bebé", max_length=80, unique=True)
    fecha_nacimiento = models.DateField("Fecha de nacimiento")

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Bebé"

class Toma(models.Model):
    bebe = models.ForeignKey(Bebe, on_delete=models.CASCADE)
    fecha = models.DateTimeField("Fecha y hora de la toma")
    cantidad_artificial = models.FloatField("Cantidad leche artificial", default=0)
    cantidad_materna = models.FloatField("Cantidad leche materna (bibe)", default=0)
    toma_teta = models.BooleanField("Ha tomado teta?", default=False)
    VALORES_TETA = [
        (0, '0 - Nada'),
        (1, '1 - Muy poco'),
        (2, '2 - Poco'),
        (3, '3 - Normal'),
        (4, '4 - Bastante'),
        (5, '5 - Mucho'),
    ]
    valor_teta = models.IntegerField("Cantidad teta", blank=True, null=True,
                                     choices=VALORES_TETA)
    comentario = models.CharField("Comentario", max_length=300, blank=True, null=True)

    def __str__(self):
        out = self.bebe.nombre + ": " + self.fecha.strftime('%a, %d/%m/%Y -- %H:%M: ')
        if self.cantidad_artificial > 0:
            out += "{:g}A  ".format(self.cantidad_artificial)
        if self.cantidad_materna > 0:
            out += "{:g}M  ".format(self.cantidad_materna)
        if self.toma_teta:
            out += "+ Teta ({}) ".format(self.valor_teta)
        if self.comentario is not None:
            out += "[" + self.comentario + "]"

        return out

class Cambio(models.Model):
    bebe = models.ForeignKey(Bebe, on_delete=models.CASCADE)
    fecha = models.DateTimeField("Fecha y hora del cambio")
    pipi = models.BooleanField("Pipí", default=False)
    caca = models.BooleanField("Caca", default=False)
    comentario = models.CharField("Comentario", max_length=300, blank=True, null=True)

    def __str__(self):
        out = self.bebe.nombre + ": " + self.fecha.strftime('%a, %d/%m/%Y -- %H:%M: ')
        if self.pipi:
            out += "Pipí"
        if self.caca:
            out += " + Caca"
        if self.comentario is not None:
            out += " [" + self.comentario + "]"

        return out

    class Meta:
        verbose_name = "Cambio de pañal"
        verbose_name_plural = "Cambios de pañal"

twindash/twinsapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Bebe, Toma, Cambio
from .plots import plot_resumen_tomas, plot_bebe_dia

import datetime


# Create your views here.
@login_required(login_url='/admin/login/')
def index(request):
    ultimas_tomas = Toma.objects.order_by("-fecha")[:10]
    ultimos_cambios = Cambio.objects.order_by("-fecha")[:10]
    lista_bebes = Bebe.objects.all()
    context = {
        'latest_tomas_list': ultimas_tomas,
        'latest_cambios_list': ultimos_cambios,
        'bebe_list': lista_bebes
        }
    return render(request, 'twinsapp/index.html', context)


@login_required(login_url='/admin/login/')
def bebe_dia(request, nombre_bebe, year, month, day):
    bebe = get_object_or_404(Bebe, nombre=nombre_bebe)
    lista_bebes = Bebe.objects.all()
    fecha = datetime.date(year, month, day)
    dia_hoy = datetime.date.today()

    tomas_bebe_hoy = Toma.objects.filter(fecha__date=fecha, bebe = bebe).order_by("-fecha")
    n_tomas_hoy = tomas_bebe_hoy.count()
    cantidad_bibe_hoy = (
        sum([x['cantidad_artificial'] for x in tomas_bebe_hoy.values()]) +
        sum([x['cantidad_materna'] for x in tomas_bebe_hoy.values()]) )
    n_tomas_teta_hoy = tomas_bebe_hoy.filter(toma_teta=True).count()

    cambios_bebe_hoy = Cambio.objects.filter(fecha__date=fecha, bebe = bebe).order_by("-fecha")
    n_cambios_hoy = cambios_bebe_hoy.count()
    n_cambios_hoy_caca = cambios_bebe_hoy.filter(caca=True).count()
    ultimo_cambio_caca = Cambio.objects.filter(caca=True, bebe=bebe).order_by("fecha").last()

    es_hoy = (fecha == dia_hoy)
    fecha_anterior = fecha - datetime.timedelta(days=1)
    fecha_posterior = fecha + datetime.timedelta(days=1)

    script_plot, div_plot = plot_bebe_dia(bebe, fecha)

    context = {
        'bebe': bebe,
        'bebe_list': lista_bebes,
        'fecha': fecha,
        'es_hoy': es_hoy,
        'fecha_anterior': fecha_anterior,
        'fecha_posterior': fecha_posterior,
        'latest_tomas_list': tomas_bebe_hoy,
        'n_tomas': n_tomas_hoy,
        'cantidad_bibe': cantidad_bibe_hoy,
        'n_tomas_teta': n_tomas_teta_hoy,
        'latest_cambios_list': cambios_bebe_hoy,
        'n_cambios': n_cambios_hoy,
        'n_cambios_caca': n_cambios_hoy_caca,
        'ultima_caca': ultimo_cambio_caca,
        'script_plot': script_plot,
        'div_plot': div_plot,
    }
    return render(request, 'twinsapp/bebe_dia.html', context)


@login_required(login_url='/admin/login/')
def main_bebe(request, nombre_bebe):
    dia_hoy = datetime.date.today()
    return bebe_dia(request, nombre_bebe, dia_hoy.year, dia_hoy.month, dia_hoy.day)

@login_required(login_url='/admin/login/')
def resumen_tomas(request):
    lista_bebes = Bebe.objects.all()
    script_plot, div_plot = plot_resumen_tomas()
    context = {
        'bebe_list': lista_bebes,
        'script_plot': script_plot,
        'div_plot': div_plot,
    }
    return render(request, 'twinsapp/resumen_tomas.html', context)

twindash/twinsapp/templates/twinsapp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="es">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'twinsapp/w3.css' %}">
    <script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.0.0.min.js"></script>
    <title>{% block title %} Maia & Vega {% endblock %}</title>
</head>

<body>
    <div id="mySidebar" class="w3-sidebar w3-light-grey w3-bar-block w3-border-right"
          style="display:none">
        <button onclick="w3_close()" class="w3-bar-item w3-large">Cerrar &times;</button>
        {% block sidebar %}
        <a href="{% url 'twinsapp:index' %}" class="w3-bar-item w3-button">Home</a>
          {% for bebe in bebe_list %}
            <a href="{% url 'twinsapp:main_bebe' bebe.nombre %}" class="w3-bar-item w3-button">{{ bebe.nombre }}</a>
            {% endfor %}
            <a href="{% url 'twinsapp:resumen_tomas' %}" class="w3-bar-item w3-button">Resumen tomas</a>
        {% endblock %}
    </div>



    <div id="header" class="w3-teal" >
      <div class="w3-cell w3-cell-middle">
      <button class="w3-button w3-teal w3-xlarge" onclick="w3_open()">☰</button>
    </div>
      <div class="w3-container w3-cell w3-cell-middle">
      <h1>{% block header %} Maia & Vega {% endblock %}</h1>
    </div>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>




    <script>
    function w3_open() {
      document.getElementById("mySidebar").style.display = "block";
    }

    function w3_close() {
      document.getElementById("mySidebar").style.display = "none";
    }
    </script>

</body>
</html>

twindash/twinsapp/templates/twinsapp/bebe.html
{% extends "twinsapp/base.html" %}

{% block header %} {{bebe.nombre}} {% endblock %}

{% block content %}

<div id="resumen" class="w3-container w3-gray" >
  <h2> Resumen de hoy ({{ hoy | date:"D, d M Y"}}) </h2>
</div>


<div class='w3-container'>
  <br>
 <div class="w3-container w3-cyan w3-cell w3-card">
   <p>{{n_tomas}} tomas hoy en total ({{n_tomas_teta}} con teta)</p>
   <p>Cantidad bibe total: {{cantidad_bibe}} ml </p>
 </div>
<div class="w3-container w3-cell"></div>
 <div class="w3-container w3-sand w3-cell w3-card">
   <p>{{n_cambios}} cambios de pañal hoy.</p>
   <p>Última caca: {{ultima_caca.fecha | date:"D, d M Y, H:i"}}
 </div>
<br>
</div>





<div id="tomas" class="w3-container w3-gray" >
  <h2> Tomas hoy </h2>
</div>

<div class="w3-container" >
  <br>
  <a href="/admin/twinsapp/toma/add" class="w3-button w3-black">Nueva toma</a>
  <a href="/admin/twinsapp/toma" class="w3-button w3-khaki"> Ver todas las tomas</a>

  {% if latest_tomas_list %}
    <table class="w3-table-all" style="width:80%">
      <tr>
        <th>Bebé</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Bibe - Artificial (ml)</th>
        <th>Bibe - Materna (ml)</th>
        <th>Toma teta?</th>
        <th>Cantidad teta</th>
        <th>Comentario</th>
        <th></th>
      </tr>
      {% for toma in latest_tomas_list %}
      <tr>
        <td>{{toma.bebe.nombre}}</td>
        <td>{{toma.fecha | date:"D, d M Y"}}</td>
        <td>{{toma.fecha | time:"H:i"}}</td>
        <td>{{toma.cantidad_artificial | floatformat}}</td>
        <td>{{toma.cantidad_materna | floatformat}}</td>
        <td>{{toma.toma_teta | yesno}}</td>
        <td>{{toma.valor_teta | default_if_none:""}}</td>
        <td>{{toma.comentario | default_if_none:""}}</td>
        <td><a href="/admin/twinsapp/toma/{{toma.id}}">Editar</a>
        <tr>
      {% endfor %}
      </table>

  {% else %}
    <p>No hay ninguna toma.</p>
  {% endif %}

</div>
<br>
<div id="cambios" class="w3-container w3-gray" >
  <h2> Cambios de pañal hoy</h2>
</div>

<div class="w3-container" >

  <br>
  <a href="/admin/twinsapp/cambio/add" class="w3-button w3-black">Nuevo cambio de pañal</a>
  <a href="/admin/twinsapp/cambio" class="w3-button w3-khaki"> Ver todos los cambios de pañal</a>
  {% if latest_cambios_list %}
    <table class="w3-table-all" style="width:80%">
      <tr>
        <th>Bebé</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Pipí</th>
        <th>Caca</th>
        <th>Comentario</th>
        <th></th>
      </tr>
      {% for cambio in latest_cambios_list %}
      <tr>
        <td>{{cambio.bebe.nombre}}</td>
        <td>{{cambio.fecha | date:"D, d M Y"}}</td>
        <td>{{cambio.fecha | time:"H:i"}}</td>
        <td>{{cambio.pipi | yesno}}</td>
        <td>{{cambio.caca | yesno}}</td>
        <td>{{cambio.comentario | default_if_none:""}}</td>
        <td><a href="/admin/twinsapp/cambio/{{cambio.id}}">Editar</a>
        <tr>
      {% endfor %}
      </table>

  {% else %}
    <p>No hay ningún cambio de pañal.</p>
  {% endif %}
</div>


{% endblock %}

twindash/twinsapp/templates/twinsapp/bebe_dia.html
{% extends "twinsapp/base.html" %}

{% block header %} {{bebe.nombre}} {% endblock %}

{% block content %}

<div id="resumen" class="w3-container w3-gray" >
  <h2> Resumen día {{ fecha | date:"D, d M Y"}} {% if es_hoy %}(hoy){% endif %} </h2>
</div>

<div class="w3-bar w3-border w3-round">
  <a href="{% url 'twinsapp:bebe_dia' bebe.nombre fecha_anterior.year fecha_anterior.month fecha_anterior.day %}"
      class="w3-button">&#10094; {{fecha_anterior | date:"d/m/Y"}}</a>
  {% if es_hoy %}
  {% else %}
  <a href="{% url 'twinsapp:bebe_dia' bebe.nombre fecha_posterior.year fecha_posterior.month fecha_posterior.day %}"
      class="w3-button w3-right">{{fecha_posterior | date:"d/m/Y"}} &#10095;</a>
  {% endif %}
</div>

<div class='w3-container'>
  <br>
 <div class="w3-container w3-cyan w3-cell w3-card">
   <p>{{n_tomas}} tomas en el día en total ({{n_tomas_teta}} con teta)</p>
   <p>Cantidad bibe total: {{cantidad_bibe}} ml </p>
 </div>
<div class="w3-container w3-cell"></div>
 <div class="w3-container w3-sand w3-cell w3-card">
   <p>{{n_cambios}} cambios de pañal en el día ({{n_cambios_caca}} con caca)</p>
   {% if es_hoy %}
   <p>Última caca: {{ultima_caca.fecha | date:"D, d M Y, H:i"}}
   {% endif %}
 </div>
<br>
</div>

<br>
<div class="w3-container" >
{{ div_plot | safe }}
</div>

{{ script_plot | safe }}




<div id="tomas" class="w3-container w3-light-gray" >
  <h3> Tomas </h3>
</div>

<div class="w3-container" >
  <br>
  <a href="/admin/twinsapp/toma/add" class="w3-button w3-black">Nueva toma</a>
  <a href="/admin/twinsapp/toma" class="w3-button w3-khaki"> Ver todas las tomas</a>

  {% if latest_tomas_list %}
    <table class="w3-table-all" style="width:80%">
      <tr>
        <th>Bebé</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Bibe - Artificial (ml)</th>
        <th>Bibe - Materna (ml)</th>
        <th>Toma teta?</th>
        <th>Cantidad teta</th>
        <th>Comentario</th>
        <th></th>
      </tr>
      {% for toma in latest_tomas_list %}
      <tr>
        <td>{{toma.bebe.nombre}}</td>
        <td>{{toma.fecha | date:"D, d M Y"}}</td>
        <td>{{toma.fecha | time:"H:i"}}</td>
        <td>{{toma.cantidad_artificial | floatformat}}</td>
        <td>{{toma.cantidad_materna | floatformat}}</td>
        <td>{{toma.toma_teta | yesno}}</td>
        <td>{{toma.valor_teta | default_if_none:""}}</td>
        <td>{{toma.comentario | default_if_none:""}}</td>
        <td><a href="/admin/twinsapp/toma/{{toma.id}}">Editar</a>
        <tr>
      {% endfor %}
      </table>

  {% else %}
    <p>No hay ninguna toma.</p>
  {% endif %}

</div>
<br>
<div id="cambios" class="w3-container w3-light-gray" >
  <h3> Cambios de pañal</h3>
</div>

<div class="w3-container" >

  <br>
  <a href="/admin/twinsapp/cambio/add" class="w3-button w3-black">Nuevo cambio de pañal</a>
  <a href="/admin/twinsapp/cambio" class="w3-button w3-khaki"> Ver todos los cambios de pañal</a>
  {% if latest_cambios_list %}
    <table class="w3-table-all" style="width:80%">
      <tr>
        <th>Bebé</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Pipí</th>
        <th>Caca</th>
        <th>Comentario</th>
        <th></th>
      </tr>
      {% for cambio in latest_cambios_list %}
      <tr>
        <td>{{cambio.bebe.nombre}}</td>
        <td>{{cambio.fecha | date:"D, d M Y"}}</td>
        <td>{{cambio.fecha | time:"H:i"}}</td>
        <td>{{cambio.pipi | yesno}}</td>
        <td>{{cambio.caca | yesno}}</td>
        <td>{{cambio.comentario | default_if_none:""}}</td>
        <td><a href="/admin/twinsapp/cambio/{{cambio.id}}">Editar</a>
        <tr>
      {% endfor %}
      </table>

  {% else %}
    <p>No hay ningún cambio de pañal.</p>
  {% endif %}
</div>


{% endblock %}

twindash/twinsapp/templates/twinsapp/index.html
{% extends "twinsapp/base.html" %}

{% block content %}

<div id="tomas" class="w3-container w3-gray" >
  <h2> Últimas tomas </h2>
</div>

<div class="w3-container" >
  <br>
  <a href="/admin/twinsapp/toma/add" class="w3-button w3-black">Nueva toma</a>
  <a href="/admin/twinsapp/toma" class="w3-button w3-khaki"> Ver todas las tomas</a>

  {% if latest_tomas_list %}
    <table class="w3-table-all" style="width:80%">
      <tr>
        <th>Bebé</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Bibe - Artificial (ml)</th>
        <th>Bibe - Materna (ml)</th>
        <th>Toma teta?</th>
        <th>Cantidad teta</th>
        <th>Comentario</th>
        <th></th>
      </tr>
      {% for toma in latest_tomas_list %}
      <tr>
        <td>{{toma.bebe.nombre}}</td>
        <td>{{toma.fecha | date:"D, d M Y"}}</td>
        <td>{{toma.fecha | time:"H:i"}}</td>
        <td>{{toma.cantidad_artificial | floatformat}}</td>
        <td>{{toma.cantidad_materna | floatformat}}</td>
        <td>{{toma.toma_teta | yesno}}</td>
        <td>{{toma.valor_teta | default_if_none:""}}</td>
        <td>{{toma.comentario | default_if_none:""}}</td>
        <td><a href="/admin/twinsapp/toma/{{toma.id}}">Editar</a>
        <tr>
      {% endfor %}
      </table>

  {% else %}
    <p>No hay ninguna toma.</p>
  {% endif %}

</div>
<br>
<div id="cambios" class="w3-container w3-gray" >
  <h2> Últimos cambios de pañal </h2>
</div>

<div class="w3-container" >

  <br>
  <a href="/admin/twinsapp/cambio/add" class="w3-button w3-black">Nuevo cambio de pañal</a>
  <a href="/admin/twinsapp/cambio" class="w3-button w3-khaki"> Ver todos los cambios de pañal</a>
  {% if latest_cambios_list %}
    <table class="w3-table-all" style="width:80%">
      <tr>
        <th>Bebé</th>
        <th>Fecha</th>
        <th>Hora</th>
        <th>Pipí</th>
        <th>Caca</th>
        <th>Comentario</th>
        <th></th>
      </tr>
      {% for cambio in latest_cambios_list %}
      <tr>
        <td>{{cambio.bebe.nombre}}</td>
        <td>{{cambio.fecha | date:"D, d M Y"}}</td>
        <td>{{cambio.fecha | time:"H:i"}}</td>
        <td>{{cambio.pipi | yesno}}</td>
        <td>{{cambio.caca | yesno}}</td>
        <td>{{cambio.comentario | default_if_none:""}}</td>
        <td><a href="/admin/twinsapp/cambio/{{cambio.id}}">Editar</a>
        <tr>
      {% endfor %}
      </table>

  {% else %}
    <p>No hay ningún cambio de pañal.</p>
  {% endif %}
</div>


{% endblock %}

twindash/twinsapp/templates/twinsapp/resumen_tomas.html
{% extends "twinsapp/base.html" %}

{% block content %}

<div id="resumen" class="w3-container w3-gray" >
  <h2> Resumen de las tomas </h2>
</div>

<br>
<div class="w3-container" >
{{ div_plot | safe }}
</div>

{{ script_plot | safe }}

{% endblock %}